import AboutMe from './components/AboutMe';
import Testimonials from './components/Testimonials';
import HomeHero from './components/HomeHero';
import HomeFaq from './components/HomeFaq';
import LegalPage from './LegalPage';
import { RetractionForm } from './StageJourney';
import { StageLanding, StageRegistration, AccompanimentLanding, OrientationPage, StagePaymentReceived, AccompanimentRequestReceived, ContactConfirmation, default as ContactPage } from './SitePages';

const legalPaths = { '/cgv': 'cgv', '/confidentialite': 'confidentialite', '/mentions-legales': 'mentions-legales', '/retractation': 'retractation' };
function Footer() { return <footer className="border-t border-slate-200 px-6 py-8 text-center text-sm text-slate-500"><div className="mx-auto flex max-w-5xl flex-wrap justify-center gap-x-6 gap-y-2"><a href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a><a href="/contact">Contact</a><a href="/cgv">CGV</a><a href="/confidentialite">Confidentialité</a><a href="/mentions-legales">Mentions légales</a><a href="/retractation">Rétractation</a></div></footer>; }
function Nav() { return <header className="border-b border-slate-200 bg-white/95 px-4 py-4 sm:px-6"><nav className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 text-[#1E3A5F]"><a href="/" className="rounded font-bold hover:text-[#3B82F6] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]">Samuel Ducros<span className="ml-2 hidden text-xs font-medium text-slate-500 sm:inline">Accompagnement Prépa</span></a><div className="flex flex-wrap gap-x-3 gap-y-2 text-sm font-semibold sm:gap-x-5"><a className="rounded hover:text-[#3B82F6] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]" href="/">Accueil</a><a className="rounded hover:text-[#3B82F6] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]" href="/stage">Stage Choc Prépa</a><a className="rounded hover:text-[#3B82F6] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]" href="/accompagnement">Accompagnement</a><a className="rounded hover:text-[#3B82F6] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]" href="/orientation">Réserver un échange</a><a className="rounded hover:text-[#3B82F6] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]" href="/contact">Contact</a></div></nav></header>; }
function MainSite() { return <><Nav /><HomeHero /><main className="px-6 py-8 sm:px-10 lg:px-20"><section className="mx-auto max-w-5xl rounded-3xl border border-blue-200 bg-blue-50 p-6 text-center sm:p-8"><p className="mx-auto max-w-3xl leading-7 text-slate-700">Vous souhaitez vérifier quelle solution correspond à la situation de votre enfant ? Réservez un échange téléphonique de 10 minutes.</p><a href="/orientation" className="mt-5 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#1E3A5F] px-5 py-3 font-bold text-white transition hover:bg-[#16304f] focus:outline-none focus:ring-2 focus:ring-[#3B82F6] focus:ring-offset-2">Réserver mon échange d’orientation <span className="ml-2">→</span></a></section><section className="mx-auto mt-8 grid max-w-6xl gap-6 lg:grid-cols-2"><article className="rounded-3xl border-2 border-[#F6B632] bg-[#FFF9EA] p-7 shadow-sm"><p className="font-bold text-[#1E3A5F]"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#F6B632]"></span>STAGE CHOC PRÉPA</p><h2 className="mt-3 text-3xl font-bold">Préparer l’entrée en prépa scientifique</h2><p className="mt-4 text-slate-600">Trois séances en visioconférence les 26, 27 et 28 août 2026.</p><a href="/stage" className="mt-6 inline-flex rounded-xl bg-[#1E3A5F] px-5 py-3 font-bold text-white">Découvrir le Stage Choc Prépa →</a></article><article className="rounded-3xl border border-[#3B82F6]/40 bg-blue-50 p-7 shadow-sm"><p className="font-bold text-[#1E3A5F]"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#3B82F6]"></span>ACCOMPAGNEMENT</p><h2 className="mt-3 text-3xl font-bold">Un suivi méthodologique pendant l’année</h2><p className="mt-4 text-slate-600">Un accompagnement en petit groupe avec un suivi ciblé de chaque étudiant.</p><a href="/accompagnement" className="mt-6 inline-flex rounded-xl bg-[#1E3A5F] px-5 py-3 font-bold text-white">Découvrir l’Accompagnement →</a></article></section><section className="mx-auto mt-16 max-w-6xl rounded-3xl bg-[#1E3A5F] p-7 text-white"><p className="font-bold text-[#F6B632]">QUELLE SOLUTION CHOISIR ?</p><div className="mt-5 grid gap-8 md:grid-cols-2"><p className="leading-7 text-slate-100"><strong className="text-white">Stage :</strong> pour préparer l’entrée en première année de CPGE scientifique.</p><p><strong>Accompagnement :</strong> pour bénéficier d’un suivi méthodologique pendant l’année.</p></div></section></main><AboutMe /><Testimonials /><HomeFaq /><section className="bg-[#1E3A5F] px-6 py-16 text-center text-white"><h2 className="text-3xl font-semibold">Une question ?</h2><div className="mt-6 flex justify-center gap-4"><a className="rounded-xl bg-[#F6B632] px-5 py-3 font-bold text-[#1E3A5F]" href="/contact">Nous contacter</a><a className="rounded-xl border border-white/50 px-5 py-3" href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a></div></section><Footer /></>; }
function Public({children}) { return <><Nav />{children}<Footer /></>; }
function NotFound() { return <Public><main className="min-h-[60vh] px-6 py-20 text-center"><h1 className="text-3xl font-bold">Cette page n’existe pas ou n’est plus disponible.</h1><div className="mt-8 flex flex-wrap justify-center gap-3"><a className="rounded-xl bg-[#1E3A5F] px-4 py-3 font-bold text-white" href="/">Accueil</a><a className="rounded-xl border px-4 py-3 font-bold" href="/stage">Stage</a><a className="rounded-xl border px-4 py-3 font-bold" href="/accompagnement">Accompagnement</a><a className="rounded-xl border px-4 py-3 font-bold" href="/contact">Contact</a></div></main></Public>; }
export default function App() { const pathname = window.location.pathname.replace(/\/$/, '') || '/'; if (pathname === '/') return <MainSite />; if (legalPaths[pathname]) return <LegalPage route={pathname} />; if (pathname === '/stage') return <Public><StageLanding /></Public>; if (pathname === '/inscription-stage') return <Public><StageRegistration /></Public>; if (pathname === '/stage/paiement-recu') return <Public><StagePaymentReceived /></Public>; if (pathname === '/accompagnement') return <Public><AccompanimentLanding /></Public>; if (pathname === '/orientation') return <Public><OrientationPage /></Public>; if (pathname === '/accompagnement/demande-recue') return <Public><AccompanimentRequestReceived /></Public>; if (pathname === '/contact') return <Public><ContactPage /></Public>; if (pathname === '/contact/message-envoye') return <Public><ContactConfirmation /></Public>; if (pathname === '/retractation-formulaire') return <Public><RetractionForm /></Public>; return <NotFound />; }
