const docs = [
  { path: '/cgv', label: 'CGV', pdf: '/documents/cgv-stage.pdf' },
  { path: '/confidentialite', label: 'Confidentialité', pdf: '/documents/politique-confidentialite.pdf' },
  { path: '/mentions-legales', label: 'Mentions légales', pdf: '/documents/mentions-legales.pdf' },
  { path: '/retractation', label: 'Rétractation', pdf: '/documents/retractation-demarrage-anticipe.pdf' },
];

function Shell({ title, children, pdf }) {
  return <main className="min-h-screen bg-[#F8FAFC] px-5 py-10 text-[#1E3A5F] sm:px-8"><article className="mx-auto max-w-4xl rounded-3xl border border-slate-200 bg-white px-6 py-8 shadow-sm sm:px-12 sm:py-12"><a href="/" className="text-sm font-semibold text-blue-600 hover:underline">← Retour au site</a><div className="mt-7 border-b-4 border-[#F6B632] pb-6"><p className="text-sm font-bold uppercase tracking-[0.16em] text-blue-600">Stage Choc Prépa</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1><p className="mt-3 text-sm text-slate-500">Version 1.0 — 29 juillet 2026</p></div><nav className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-sm font-semibold text-blue-700">{docs.map((item) => <a className="hover:underline" href={item.path} key={item.path}>{item.label}</a>)}</nav><div className="legal-content mt-10 space-y-8">{children}</div><div className="mt-12 border-t border-slate-200 pt-6 text-sm"><a className="font-semibold text-blue-700 hover:underline" href={pdf} download>Télécharger ce document au format PDF</a></div></article></main>;
}
function Section({ title, children }) { return <section><h2 className="text-xl font-bold">{title}</h2><div className="mt-3 space-y-3 leading-7 text-slate-700">{children}</div></section>; }

function Cgv() { return <Shell title="Conditions générales de vente" pdf="/documents/cgv-stage.pdf">
  <Section title="1. Identité du prestataire"><p>Samuel DUCROS EI, entrepreneur individuel au régime micro-BNC.</p><p>SIREN 935 013 094<br />15 rue de Villefranche, 34090 Montpellier<br />contact@samuel-ducros.fr</p><p>TVA non applicable, art. 293 B du CGI.</p></Section>
  <Section title="2. Objet et documents contractuels"><p>Les présentes CGV régissent les ventes à des consommateurs. La commande est conclue en ligne après présentation des informations précontractuelles, acceptation des CGV et paiement. L’e-mail de confirmation envoyé après paiement et contrôle de capacité constitue le support durable récapitulant la commande.</p></Section>
  <Section title="3. Offres et prix"><p><strong>Stage Choc Prépa</strong><br />Prix total : 149 €. TVA non applicable, art. 293 B du CGI.</p></Section>
  <Section title="4. Conclusion du contrat et place"><p>Avant le paiement, le client accède aux informations précontractuelles, aux présentes CGV, à la <a href="/confidentialite">politique de confidentialité</a>, aux informations relatives à la médiation de la consommation et au <a href="/retractation">formulaire de rétractation</a>. Pour le Stage Choc Prépa, l’e-mail de confirmation envoyé après paiement et contrôle de capacité constitue le support durable récapitulant la commande.</p></Section>
  <Section title="5. Paiement"><p>Le paiement du Stage Choc Prépa s’effectue en ligne par carte bancaire via Stripe. Le prix de 149 € est exigible en totalité lors de la commande.</p><p>En cas d’échec de paiement, le prestataire contacte le client et peut suspendre l’accès aux prestations futures jusqu’à régularisation, sans préjudice des droits légaux du consommateur. Toute résiliation ou remboursement est traité au regard des circonstances, de la prestation déjà exécutée et des droits impératifs du consommateur.</p></Section>
  <Section title="6. Exécution de la prestation"><p>Le contenu, les dates, le format, le groupe et les éventuels supports sont présentés avant la commande et récapitulés dans l’e-mail de confirmation. Le prestataire est tenu d’une obligation de moyens et ne garantit ni résultat scolaire, ni admission, ni progression chiffrée.</p><p>Une séance collective manquée par l’étudiant n’ouvre pas automatiquement droit à un rattrapage individuel. Les supports prévus restent accessibles selon les conditions de l’offre.</p></Section>
  <Section title="7. Droit de rétractation — vente à distance"><p>Sauf exception légale, le consommateur dispose de 14 jours à compter de la conclusion du contrat pour se rétracter sans motif. Le formulaire type est accessible sur la page <a href="/retractation">Rétractation</a>.</p><p>Si le client demande expressément que la prestation commence avant la fin de ce délai, il doit compléter la demande distincte prévue à cet effet. En cas de rétractation après le début demandé, il reste redevable d’un montant proportionné à ce qui aura été exécuté. La perte du droit de rétractation ne peut intervenir qu’aux conditions légales, notamment après exécution complète et accord/renoncement exprès lorsque requis.</p><p>Les remboursements légalement dus sont réalisés dans les délais applicables.</p></Section>
  <Section title="8. Absences, reports, interruption"><p>Toute absence doit être signalée dès que possible. Les règles particulières de report, interruption ou remboursement éventuellement convenues figurent au bon de commande ; elles ne limitent pas les droits impératifs du consommateur. Une modification substantielle imputable au prestataire donne lieu à une solution adaptée proposée au client.</p></Section>
  <Section title="9. Données personnelles"><p>Les modalités de traitement des données sont décrites dans la <a href="/confidentialite">politique de confidentialité</a>. Le client peut exercer ses droits à contact@samuel-ducros.fr. Les données ne sont utilisées que pour la gestion de la relation, la prestation et les obligations légales applicables.</p></Section>
  <Section title="10. Réclamations et médiation"><p>Toute réclamation est adressée d’abord par écrit à contact@samuel-ducros.fr.</p><p>En cas de litige entre le Client et le prestataire, ils s’efforcent de le résoudre à l’amiable. À défaut d’accord amiable, ou sans réponse dans un délai raisonnable d’un mois, le Client consommateur peut saisir gratuitement le médiateur de la consommation compétent :</p><p>Société Médiation Professionnelle<br /><a href="https://www.mediateur-consommation-smp.fr">https://www.mediateur-consommation-smp.fr</a><br />Alteritae, 5 rue Salvaing, 12000 Rodez.</p><p>La médiation est mise en œuvre à l’initiative du consommateur, dans les conditions prévues par le Code de la consommation.</p></Section>
  <Section title="11. Droit applicable"><p>Les présentes CGV sont soumises au droit français. Elles ne privent pas le consommateur des dispositions impératives qui lui sont applicables.</p></Section>
</Shell>; }

function Privacy() { return <Shell title="Politique de confidentialité" pdf="/documents/politique-confidentialite.pdf">
  <Section title="1. Responsable du traitement"><p>Samuel DUCROS EI<br />15 rue de Villefranche, 34090 Montpellier<br />contact@samuel-ducros.fr</p></Section>
  <Section title="2. Données traitées"><p>Données d’identification et de contact du parent/client et de l’étudiant ; informations de scolarité strictement nécessaires à l’accompagnement ; échanges liés à la prestation ; données de paiement traitées par le prestataire de paiement ; données techniques des outils utilisés.</p><p>Ne pas transmettre de données de santé ou autre donnée sensible non nécessaire.</p></Section>
  <Section title="3. Finalités"><p>Répondre aux demandes, qualifier un besoin, conclure et exécuter le contrat, organiser les groupes/séances, communiquer les informations utiles, gérer les paiements et factures, traiter les réclamations, respecter les obligations légales et protéger les accès aux outils.</p></Section>
  <Section title="4. Bases et destinataires"><p>Les traitements nécessaires au contrat reposent sur son exécution ; ceux nécessaires à la comptabilité ou à la gestion des litiges reposent sur les obligations légales ou l’intérêt légitime applicable ; les consentements distincts sont recueillis lorsque requis.</p><p>Les données sont accessibles seulement au prestataire et aux sous-traitants nécessaires : Google Workspace, Stripe, Zoom, Meta, Tally et Make, ainsi que le service de messagerie utilisé pour la relation client. Les données ne sont pas vendues.</p></Section>
  <Section title="5. Conservation"><p>Prospects non clients : trois ans à compter de la collecte ou du dernier contact émanant du prospect, sauf opposition ou besoin d’archivage légal.</p><p>Dossier contractuel : pendant l’exécution de la prestation, puis cinq ans à compter de la fin du contrat en archivage à accès limité, sous réserve d’une obligation légale plus longue.</p><p>Pièces comptables et factures : dix ans à compter de leur émission ou réception, conformément aux obligations applicables.</p><p>Les données sont supprimées ou anonymisées à l’issue de ces durées, sauf obligation légale, exercice ou défense d’un droit en justice.</p></Section>
  <Section title="6. Droits"><p>Toute personne peut demander l’accès, la rectification, l’effacement, la limitation, l’opposition ou la portabilité lorsque ces droits sont applicables, à contact@samuel-ducros.fr. En cas de difficulté non résolue, une réclamation peut être adressée à la CNIL.</p></Section>
  <Section title="7. Sécurité"><p>Le prestataire limite les accès aux seules personnes nécessaires, utilise des comptes protégés, applique des accès individualisés lorsque l’outil le permet et évite toute diffusion publique.</p></Section>
  <Section title="8. Mineurs"><p>Les données d’un étudiant mineur sont traitées pour la prestation convenue avec son représentant légal.</p></Section>
</Shell>; }

function Legal() { return <Shell title="Mentions légales" pdf="/documents/mentions-legales.pdf"><Section title="Éditeur du site"><p>Samuel DUCROS EI, entrepreneur individuel.<br />SIREN : 935 013 094.<br />Adresse : 15 rue de Villefranche, 34090 Montpellier.<br />E-mail : contact@samuel-ducros.fr.<br />TVA non applicable, art. 293 B du CGI.<br />Directeur de la publication : Samuel Ducros.</p></Section><Section title="Hébergeur"><p>Vercel Inc.<br />440 N Barranca Avenue #4133<br />Covina, CA 91723<br />États-Unis<br /><a href="https://vercel.com/contact">https://vercel.com/contact</a></p></Section><Section title="Médiation de la consommation"><p>Société Médiation Professionnelle, Alteritae, 5 rue Salvaing, 12000 Rodez — <a href="https://www.mediateur-consommation-smp.fr">www.mediateur-consommation-smp.fr</a>.</p></Section></Shell>; }

function Retraction() { return <Shell title="Rétractation et demande de démarrage anticipé" pdf="/documents/retractation-demarrage-anticipe.pdf"><p className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-slate-700">Le formulaire de rétractation en ligne est préparé pour le parcours. Après son envoi, Samuel DUCROS EI reçoit une notification immédiate et vous adresse un accusé de réception par e-mail dès qu’il en prend connaissance.  
En attendant son ouverture, une déclaration claire peut être adressée à <a href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a>.</p><Section title="Formulaire type de rétractation"><p>À compléter et renvoyer uniquement si vous souhaitez vous rétracter du contrat.</p><p>À l’attention de :<br />Samuel DUCROS EI<br />15 rue de Villefranche<br />34090 Montpellier<br />contact@samuel-ducros.fr</p><p>Je vous notifie par la présente ma rétractation du contrat portant sur la prestation ci-après :</p><p><strong>Prestation commandée :</strong> ____________________________<br /><strong>Commandée le :</strong> ____________________________<br /><strong>Nom du consommateur :</strong> ____________________________<br /><strong>Adresse du consommateur :</strong> ____________________________<br /><strong>Date :</strong> ____________________________<br /><strong>Signature du consommateur :</strong> uniquement en cas d’envoi papier.</p><p>Vous pouvez également adresser toute déclaration claire exprimant votre volonté de vous rétracter à contact@samuel-ducros.fr. Le droit de rétractation est expliqué dans les <a href="/cgv">CGV</a>.</p></Section><Section title="Demande expresse de commencement avant la fin du délai de rétractation"><p>Cette partie ne doit être complétée que si le client souhaite que la prestation commence avant l’expiration du délai légal de rétractation.</p><p>Je soussigné(e) _________________________________, demande expressément à Samuel DUCROS EI de commencer l’exécution de la prestation ______________________ avant la fin du délai de rétractation.</p><p>Je reconnais avoir été informé(e) que, si j’exerce mon droit de rétractation après le début de l’exécution demandé, je devrai verser un montant proportionné à ce qui aura été exécuté jusqu’à ma notification de rétractation, dans les conditions légales.</p><p>Je reconnais également qu’en cas d’exécution complète de la prestation avant la fin du délai de rétractation, la perte du droit de rétractation ne peut intervenir que dans les conditions prévues par la loi et après les consentements requis.</p><p>Date : ____________________<br />Nom : ____________________<br />Signature : ____________________</p></Section></Shell>; }

export default function LegalPage({ route }) { if (route === '/cgv') return <Cgv />; if (route === '/confidentialite') return <Privacy />; if (route === '/mentions-legales') return <Legal />; return <Retraction />; }
