import { useState } from 'react';

const docs = [
  { path: '/cgv', label: 'CGV' },
  { path: '/confidentialite', label: 'Confidentialité' },
  { path: '/mentions-legales', label: 'Mentions légales' },
  { path: '/retractation', label: 'Rétractation' },
];

function Shell({ title, children }) {
  return <main className="min-h-screen bg-[#F8FAFC] px-5 py-10 text-[#1E3A5F] sm:px-8"><article className="mx-auto max-w-4xl rounded-3xl border border-slate-200 bg-white px-6 py-8 shadow-sm sm:px-12 sm:py-12"><a href="/" className="text-sm font-semibold text-blue-600 hover:underline">← Retour au site</a><div className="mt-7 border-b-4 border-[#F6B632] pb-6"><p className="text-sm font-bold uppercase tracking-[0.16em] text-blue-600">Accompagnement CPGE</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1></div><nav className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-sm font-semibold text-blue-700">{docs.map((item) => <a className="hover:underline" href={item.path} key={item.path}>{item.label}</a>)}</nav><div className="legal-content mt-10 space-y-8">{children}</div></article></main>;
}
function Section({ title, children }) { return <section><h2 className="text-xl font-bold">{title}</h2><div className="mt-3 space-y-3 leading-7 text-slate-700">{children}</div></section>; }

function Cgv() { return <Shell title="Conditions générales de vente">
  <Section title="1. Identité du prestataire"><p>Samuel Ducros EI, entrepreneur individuel<br />SIREN 935 013 094<br />15 rue de Villefranche, 34090 Montpellier, France<br /><a href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a><br />TVA non applicable, article 293 B du CGI.</p></Section>
  <Section title="2. Objet de l’accompagnement"><p>Samuel Ducros EI propose un accompagnement CPGE collectif à distance, organisé en groupes de trois étudiants maximum. Chaque cycle comprend douze séances hebdomadaires de deux heures, soit vingt-quatre heures au total. Le créneau, le niveau, les dates et le groupe sont définis dans le contrat et son annexe individuelle.</p><p>Le prestataire est tenu d’une obligation de moyens et ne garantit ni résultat scolaire, ni admission, ni progression chiffrée.</p></Section>
  <Section title="3. Prix et règlement"><p>Le prix total est de 1 110 €, TVA non applicable, article 293 B du CGI. Règlement comptant ou trois échéances mensuelles de 370 €, par virement, sans intérêt, frais, abonnement ni reconduction automatique.</p></Section>
  <Section title="4. Réservation et confirmation de place"><p>Après diagnostic et accord sur un créneau compatible, une place peut être pré-réservée jusqu’à la date limite de l’annexe individuelle. L’inscription est confirmée par e-mail après acceptation du contrat, encaissement du premier paiement exigible et confirmation de la capacité du groupe.</p></Section>
  <Section title="5. Absences"><p>Une absence individuelle ne donne pas droit automatiquement à un rattrapage individuel, une prolongation personnelle ou un remboursement automatique, sous réserve des droits légaux applicables.</p></Section>
  <Section title="6. Durée"><p>Le contrat couvre un cycle unique de douze semaines, sans tacite reconduction ; tout renouvellement requiert un nouvel accord écrit.</p></Section>
  <Section title="7. Droit de rétractation"><p>En vente à distance, le client dispose d’un délai de quatorze jours à compter de la conclusion du contrat pour se rétracter, sans motif ni pénalité. Le commencement avant la fin de ce délai ne peut intervenir que sur une demande expresse distincte, datée et liée au contrat précis.</p><p>La page <a className="font-semibold text-blue-700 underline" href="/retractation">Rétractation</a> permet de préparer l’e-mail de rétractation ou d’obtenir les informations nécessaires pour adresser une déclaration claire à contact@samuel-ducros.fr.</p></Section>
  <Section title="8. Données personnelles"><p>Les modalités de traitement des données sont décrites dans la <a className="font-semibold text-blue-700 underline" href="/confidentialite">politique de confidentialité</a>.</p></Section>
  <Section title="9. Réclamations et médiation"><p>Toute réclamation peut être adressée à <a href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a>.</p><p>En cas de litige, le Client consommateur peut saisir gratuitement le médiateur de la consommation compétent : Société Médiation Professionnelle, Alteritae, 5 rue Salvaing, 12000 Rodez — <a href="https://www.mediateur-consommation-smp.fr">https://www.mediateur-consommation-smp.fr</a>.</p></Section>
</Shell>; }

function Privacy() { return <Shell title="Politique de confidentialité">
  <Section title="1. Responsable du traitement"><p>Samuel Ducros EI est responsable du traitement des données personnelles.</p></Section>
  <Section title="2. Données traitées"><p>Les données concernent le parent ou client, l’étudiant, le niveau ou la filière, les éléments de qualification, les disponibilités, le contrat et la facturation.</p></Section>
  <Section title="3. Finalités"><p>Les données sont utilisées pour la qualification, le diagnostic, l’exécution de l’accompagnement, la facturation, les réclamations et le respect des obligations légales.</p></Section>
  <Section title="4. Bases légales"><p>Les traitements reposent sur les mesures précontractuelles, le contrat et les obligations légales. Un consentement distinct est demandé lorsque nécessaire pour les replays et la prospection.</p></Section>
  <Section title="5. Outils utilisés"><p>Selon les usages réels, les outils concernés sont Meta, Make, Google Workspace (Gmail, Drive, Sheets et Calendar), Zoom, Brevo, Shine et Trustpilot.</p></Section>
  <Section title="6. Durées de conservation"><p>Les données de prospect sont conservées trois ans après le dernier contact. Les données contractuelles sont conservées pendant la relation, puis en archivage limité. Les factures sont conservées dix ans. L’opposition à la prospection est conservée trois ans. Les replays sont conservés trente jours ; le consentement relatif aux replays et les pièces utiles à un litige sont conservés cinq ans en archivage restreint.</p></Section>
  <Section title="7. Vos droits"><p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition ou la portabilité de vos données lorsque ces droits sont applicables. Pour les exercer, écrivez à <a href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a>. En cas de difficulté non résolue, vous pouvez introduire une réclamation auprès de la CNIL.</p></Section>
  <Section title="8. Décision automatisée"><p>Aucune décision automatisée produisant un effet juridique n’est prise à partir de vos données.</p></Section>
</Shell>; }

function Legal() { return <Shell title="Mentions légales"><Section title="Éditeur du site"><p>Samuel Ducros EI, entrepreneur individuel<br />SIREN 935 013 094<br />15 rue de Villefranche, 34090 Montpellier, France<br /><a href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a><br />Directeur de la publication : Samuel Ducros</p></Section><Section title="Hébergeur"><p>Cloudflare, Inc.<br />101 Townsend St.<br />San Francisco, CA 94107<br />États-Unis</p></Section><Section title="Médiation de la consommation"><p>Société Médiation Professionnelle<br />Alteritae, 5 rue Salvaing, 12000 Rodez<br /><a href="https://www.mediateur-consommation-smp.fr">https://www.mediateur-consommation-smp.fr</a></p></Section></Shell>; }

function Retraction() { return <Shell title="Rétractation"><p className="rounded-2xl border border-amber-300 bg-amber-50 p-5 leading-7 text-slate-700">Vous pouvez exercer votre droit de rétractation dans les quatorze jours suivant la conclusion de votre contrat, sans motif ni pénalité. Vous pouvez utiliser la page suivante pour préparer l’e-mail de rétractation, puis l’envoyer depuis votre messagerie, ou adresser toute déclaration claire à <a className="font-semibold text-blue-700 underline" href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a>.</p><div className="mt-6"><a href="/retractation-formulaire" className="inline-flex rounded-xl bg-[#1E3A5F] px-5 py-3 font-bold text-white hover:bg-[#16304f]">Préparer l’e-mail de rétractation <span className="ml-2">→</span></a></div><Section title="Démarrage anticipé"><p>Le commencement avant la fin du délai de rétractation ne peut intervenir que sur une demande expresse distincte, datée et liée au contrat précis.</p></Section></Shell>; }

export function RetractionForm() {
  const [sent, setSent] = useState(false);
  const submit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const subject = encodeURIComponent(`Rétractation — ${data.get('firstName')} ${data.get('lastName')}`); const body = encodeURIComponent(`Nom : ${data.get('lastName')}\nPrénom : ${data.get('firstName')}\nE-mail : ${data.get('email')}\nRéférence ou date du contrat : ${data.get('contract')}\nDate : ${data.get('date')}\n\nDéclaration de rétractation :\n${data.get('statement')}`); window.location.href = `mailto:contact@samuel-ducros.fr?subject=${subject}&body=${body}`; setSent(true); };
  return <Shell title="Formulaire de rétractation"><p className="leading-7 text-slate-700">Vous pouvez exercer votre droit de rétractation dans les quatorze jours suivant la conclusion de votre contrat, sans motif ni pénalité.</p><form onSubmit={submit} className="mt-8 rounded-3xl border border-slate-200 bg-[#F8FAFC] p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label>Nom<input required name="lastName" className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><label>Prénom<input required name="firstName" className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" /></label></div><label className="mt-5 block">Adresse e-mail<input required type="email" name="email" className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><label className="mt-5 block">Référence ou date du contrat<input required name="contract" className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><label className="mt-5 block">Déclaration de rétractation<textarea required name="statement" rows="5" className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><label className="mt-5 block">Date<input required type="date" name="date" className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><button className="mt-6 rounded-xl bg-[#1E3A5F] px-5 py-3 font-bold text-white hover:bg-[#16304f]">Préparer l’e-mail de rétractation</button>{sent && <p className="mt-4 text-sm text-slate-600">Votre messagerie s’ouvre avec les informations du formulaire. Envoyez ensuite l’e-mail pour transmettre votre demande.</p>}</form><p className="mt-6 text-sm leading-6 text-slate-600">Vous pouvez aussi adresser toute déclaration claire à <a className="font-semibold text-blue-700 underline" href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a>.</p></Shell>;
}

export default function LegalPage({ route }) { if (route === '/cgv') return <Cgv />; if (route === '/confidentialite') return <Privacy />; if (route === '/mentions-legales') return <Legal />; return <Retraction />; }
