const FORM_URL = '';
const PAYMENT_URL = '';
const RETRACTION_URL = '';

function Button({ href, children }) {
  return href ? <a href={href} className="inline-flex rounded-xl bg-[#1E3A5F] px-5 py-3 font-bold text-white hover:bg-[#16304f]">{children} <span className="ml-2">→</span></a> : <span className="inline-flex cursor-not-allowed rounded-xl bg-slate-300 px-5 py-3 font-bold text-slate-600">{children}<small className="ml-2 rounded bg-white/60 px-2 py-0.5 uppercase">à compléter</small></span>;
}
function Shell({ eyebrow, title, intro, children }) {
  return <main className="min-h-screen bg-[#F8FAFC] px-5 py-8 text-[#1E3A5F] sm:px-8 sm:py-12"><article className="mx-auto max-w-5xl"><a href="/" className="text-sm font-semibold text-blue-600 hover:underline">← Retour au site</a><header className="mt-8 rounded-3xl bg-white px-6 py-9 shadow-sm ring-1 ring-slate-200 sm:px-10"><p className="text-sm font-bold uppercase tracking-[0.16em] text-blue-600">{eyebrow}</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{intro}</p></header>{children}</article></main>;
}
function Card({ n, title, children }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#F6B632] font-bold">{n}</span><div><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 leading-7 text-slate-600">{children}</p></div></div></div>;
}
const automaticEligibility = 'élèves entrant à la rentrée 2026 en première année de MPSI, MP2I, PCSI ou PTSI';
const manualReviewEligibility = 'Les entrants en BCPST, TSI ou toute autre première année de CPGE scientifique font l’objet d’une vérification pédagogique manuelle avant toute proposition de paiement.';

export function StageHome() {
  return <Shell eyebrow="Stage Choc Prépa" title="Préparer son entrée en prépa scientifique" intro={`Un stage intensif de trois séances en direct, du 19 au 21 août 2026, pour les ${automaticEligibility}.`}>
    <section className="mt-8 grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-[#1E3A5F] p-6 text-white"><p className="text-sm font-bold uppercase text-[#F6B632]">Format</p><p className="mt-3 text-lg font-semibold">3 séances en direct de 2 h 30</p></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-bold uppercase text-blue-600">Tarif</p><p className="mt-3 text-lg font-semibold">149 €</p></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-bold uppercase text-blue-600">Places</p><p className="mt-3 text-lg font-semibold">20 places maximum</p></div></section>
    <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><h2 className="text-2xl font-bold">Comment se déroule l’inscription ?</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><Card n="1" title="Demande d’inscription">Le parent renseigne les informations nécessaires pour l’élève.</Card><Card n="2" title="Vérification">Nous vérifions la filière et la disponibilité d’une place.</Card><Card n="3" title="Paiement puis confirmation">Le paiement est proposé seulement si une place est disponible ; la confirmation suit le paiement réussi et le contrôle de capacité.</Card></div><p className="mt-7 rounded-xl bg-slate-100 px-5 py-4 text-sm leading-6 text-slate-600">Les inscriptions ne sont pas encore ouvertes. Aucun formulaire ni paiement n’est accessible depuis cette page avant le feu vert de production.</p></section>
    <section className="mt-8 rounded-2xl border border-[#F6B632] bg-[#FFF9EA] p-6 text-slate-700"><h2 className="font-bold text-[#1E3A5F]">Déjà inscrit·e ?</h2><p className="mt-2 leading-7">Pour exercer votre droit de rétractation, utilisez le formulaire dédié. La demande est traitée manuellement ; la notification de réception ne vaut pas confirmation du remboursement.</p><a href="/retractation-formulaire" className="mt-4 inline-block font-bold text-blue-700 hover:underline">Accéder au formulaire de rétractation →</a></section>
  </Shell>;
}
export function StageRegistration() {
  return <Shell eyebrow="Stage Choc Prépa · demande d’inscription" title="Demander une place" intro="Cette demande ne constitue pas encore une inscription définitive. Le paiement n’est proposé qu’après vérification de l’éligibilité et de la capacité du groupe.">
    <section className="mt-8 grid gap-5 md:grid-cols-[1.3fr_0.7fr]"><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-9"><h2 className="text-2xl font-bold">Avant de commencer</h2><ul className="mt-5 space-y-3 leading-7 text-slate-700"><li>• Éligibilité automatique : {automaticEligibility}.</li><li>• {manualReviewEligibility}</li><li>• Terminale, deuxième année, indisponibilité pour les trois séances ou refus du format collectif : non-éligible au Stage.</li><li>• Préparez le nom de l’élève, sa filière et les coordonnées du parent responsable légal.</li><li>• La politique de confidentialité est accessible dans le formulaire.</li></ul><div className="mt-7"><Button href={FORM_URL}>Ouvrir le formulaire d’inscription</Button></div><p className="mt-4 text-sm leading-6 text-slate-500">Le formulaire d’inscription sera accessible à l’ouverture du parcours.</p></div><aside className="rounded-3xl bg-[#1E3A5F] p-7 text-white"><p className="text-sm font-bold uppercase text-[#F6B632]">À retenir</p><p className="mt-4 text-lg font-semibold leading-8">Le paiement réussi ne confirme pas seul une place : la confirmation est envoyée après vérification de capacité.</p><a href="/cgv" className="mt-6 inline-block font-semibold underline">Lire les CGV</a></aside></section>
  </Shell>;
}
export function StagePayment() {
  return <Shell eyebrow="Stage Choc Prépa · paiement" title="Finaliser l’inscription" intro="Cette page est prévue pour le parent après validation de la demande et contrôle d’une place disponible.">
    <section className="mt-8 rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-10"><div className="grid gap-7 md:grid-cols-[1fr_auto] md:items-center"><div><h2 className="text-2xl font-bold">Stage Choc Prépa — 149 €</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Paiement unique et sécurisé par Stripe. Les CGV et la politique de confidentialité sont consultables avant paiement. Une facture PDF Stripe est générée selon la configuration retenue.</p><p className="mt-4 font-semibold text-[#1E3A5F]">L’inscription est confirmée après paiement et contrôle de capacité. Vous recevrez une confirmation par e-mail.</p></div><Button href={PAYMENT_URL}>Accéder au paiement sécurisé</Button></div><div className="mt-8 grid gap-4 border-t border-slate-200 pt-7 md:grid-cols-3"><Card n="1" title="Paiement">Carte bancaire via Stripe.</Card><Card n="2" title="Contrôle">Paiement validé et capacité contrôlée.</Card><Card n="3" title="Confirmation">E-mail de confirmation et facture envoyés au parent.</Card></div></section><p className="mt-6 text-center text-sm text-slate-500">Besoin d’exercer votre droit de rétractation ? <a className="font-semibold text-blue-700 hover:underline" href="/retractation-formulaire">Accéder au formulaire dédié</a>.</p>
  </Shell>;
}
export function RetractionForm() {
  return <Shell eyebrow="Stage Choc Prépa · rétractation" title="Exercer votre droit de rétractation" intro="Vous pouvez transmettre votre demande au moyen du formulaire en ligne. Elle est enregistrée et horodatée, puis traitée manuellement.">
    <section className="mt-8 grid gap-5 md:grid-cols-[1.25fr_0.75fr]"><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-9"><h2 className="text-2xl font-bold">Formulaire de rétractation</h2><p className="mt-3 leading-7 text-slate-700">Le formulaire recueillera les informations prévues par le document de rétractation validé : prestation commandée, date de commande, identité et adresse du consommateur, et déclaration de rétractation.</p><div className="mt-7"><Button href={RETRACTION_URL}>Ouvrir le formulaire de rétractation</Button></div><p className="mt-4 text-sm leading-6 text-slate-500">Le formulaire Tally est horodaté et notifie Samuel immédiatement. Samuel adresse l’accusé de réception au parent dès qu’il en prend connaissance. La notification Tally est interne et ne constitue pas cet accusé.</p></div><aside className="rounded-3xl border border-[#F6B632] bg-[#FFF9EA] p-7 text-slate-700"><h2 className="text-lg font-bold text-[#1E3A5F]">Autre possibilité</h2><p className="mt-3 leading-7">Vous pouvez aussi adresser toute déclaration claire à <a className="font-semibold text-blue-700 underline" href="mailto:contact@samuel-ducros.fr">contact@samuel-ducros.fr</a>.</p><a href="/retractation" className="mt-5 inline-block font-semibold text-blue-700 hover:underline">Lire le document complet de rétractation →</a></aside></section>
  </Shell>;
}
